# Generated by Django 5.0.4 on 2024-09-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='contacts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.contactsuser', verbose_name='Контакты'),
        ),
    ]
