# Generated by Django 5.0.4 on 2024-09-12 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.contactsuser', verbose_name='Контакты'),
        ),
    ]
