# Generated by Django 5.0.4 on 2024-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_parameter_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Внешний идентификатор'),
        ),
    ]
